### ISSUE TITLE
To Dos after the move

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/node-red#1]
The move has finished. The contributors look correct now.

- [x] Publishing to npm
- [x] Agreeing on the versioning
- [x] Deprecating older packages (including @hidetak packages)
- [x] Making old repo a public archive
- [x] Evaluating [the existing issues](https://github.com/thingweb/node-red-contrib-web-of-things/issues) if they are still issues

**Comment by hidetak** [comment]
@egekorkan @JKRhb 

> Evaluating [the existing issues](https://github.com/thingweb/node-red-contrib-web-of-things/issues) if they are still issues

Along with the server-side node development, I have modified the following Issue to meet the request.
https://github.com/thingweb/node-red-contrib-web-of-things/issues/17

**Comment by hidetak** [comment]
> Deprecating older packages (including @hidetak packages)

I will deprecate my package after a new package is released.

**Comment by egekorkan** [comment]
ok it seems I cannot comment when the repo is archived or close an issue. In the next meeting, we can evaluate which way to go. I am fine by leaving the issues open, it is unlikely that someone will trace back there. We should simply open the issues here if they are still present. Any thoughts @danielpeintner , @relu91, @JKRhb ?

**Comment by danielpeintner** [comment]
I agree, we should
* open the _same_ issues here again (if still valid)
* add a pointer to its new location (I did not find it)

Maybe we can temporarily **un**-archive the old repo to close all old issues and add a BIG Header were the new content went...

**Comment by egekorkan** [comment]
I have unarchived it and closed all the non-relevant issues. There is only https://github.com/thingweb/node-red-contrib-web-of-things/issues/12 left that I think we can move here since we were discussing it in the last meeting. 

I have also added a warning banner on the top of the readme.

**Comment by egekorkan** [comment]
In today's call, we have fixed the versioning and then will publish to npm after integrating prettier and eslint workflow.

**Comment by egekorkan** [comment]
@hidetak the packages are published to npm https://www.npmjs.com/package/@thingweb/node-red-node-wot and also available in flows library at https://flows.nodered.org/node/@thingweb/node-red-node-wot . 

Still some small todos:
- @hidetak can you deprecate your packages?
- We need to find a way to deprecate https://www.npmjs.com/package/node-red-contrib-web-of-things since I do not have access in any way. @sebastiankb or @danielpeintner any idea? I pinged you since you are in the organization that published the package.

**Comment by hidetak** [comment]
@egekorkan 

Thank you for making the package available to the public.

> * @hidetak can you deprecate your packages?

I have changed to deprecated.
https://www.npmjs.com/package/@hidetak/node-red-contrib-web-of-things

**Comment by egekorkan** [comment]
Thank you @hidetak. I have deprecated the old ones as well after getting access to the organization. The todos are completed, closing issue :)
