### ISSUE TITLE
Refactor binding finder

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/node-red#17]
> After the discussions today, a real solution will take some time land and I would not want to block this PR. I propose to merge this PR and create an issue to track this. Once https://github.com/eclipse-thingweb/td-tools/issues/18 is done, we can do the work to integrate it here. @danielpeintner @relu91 any opinions?

_Originally posted by @egekorkan in https://github.com/eclipse-thingweb/node-red/pull/16#discussion_r1581000782_

**Comment by egekorkan** [comment]
https://github.com/eclipse-thingweb/td-tools/issues/18 will tackle this

**Comment by egekorkan** [comment]
With https://www.npmjs.com/package/@thingweb/td-utils published, we can use it here now.

**Comment by hasanheroglu** [comment]
I'll handle this.
