### ISSUE TITLE
Pre-built code is registered in npmjs

### ISSUE THREAD

**Issue by hidetak** [eclipse-thingweb/node-red#28]
The @thingweb/node-red-node-wot v1.2.2 code registered in npmjs is the code before the build (v1.2.1 code).
https://www.npmjs.com/package/@thingweb/node-red-node-wot?activeTab=code
(The code in the `dist` and `resources` folders was out of date)

@egekorkan 

I apologize for the inconvenience, but could you please build it and register it with npmjs?

Sorry for the delay in confirming this.
Thank you very much.

**Comment by egekorkan** [comment]
@hidetak my mistake for sure :/ I have published 1.2.3 now :)

**Comment by hidetak** [comment]
@egekorkan 
Thank you for your prompt response!
This issue has been closed.

**Comment by egekorkan** [comment]
My pleasure, thank you for reporting in the first place!
