### ISSUE TITLE
Improving scorecard

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/node-red#7]
We should check https://flows.nodered.org/node/@thingweb/node-red-node-wot/scorecard and improve the checklist.

**Comment by egekorkan** [comment]
All points except for example nodes are addressed but the scorecard is not updated for some reason.

**Comment by hidetak** [comment]
As you may already know, you can check scorecard on your own PC with the following npm module.
https://www.npmjs.com/package/node-red-dev

I will also look into the scorecard to see if it can be improved.

**Comment by egekorkan** [comment]
I have published the new version but the scorecard did not update. It seems that it doesn't update after initial release,  which is a bit of a weird bug. See https://discourse.nodered.org/t/node-red-flows-scorecard-do-not-update/77655/6

**Comment by egekorkan** [comment]
Fixed by the node-red team. Closing
