### ISSUE TITLE
Add a node to extract Thing Description

### ISSUE THREAD

**Issue by hidetak** [eclipse-thingweb/node-red#8]
I would like to develop a node that extracts Thing Description (JSON) generated by a server-side WoT node.
One of the use cases for this node is to register Thing Descriptions with the TD Directory using flows.
I believe that being able to register with flow will allow us to flexibly respond to a variety of TD Directories.

I would also like to add a node that sets the TD on the client side so that the Thing Description get from the TD Directory can be set dynamically.

**Comment by egekorkan** [comment]
> I would like to develop a node that extracts Thing Description (JSON) generated by a server-side WoT node.

@hidetak sounds like a good idea. It would be like using the getThingDescription of node-wot I guess?

> I would also like to add a node that sets the TD on the client side so that the Thing Description get from the TD Directory can be set dynamically.

Sounds also reasonable and applicable to local network discovery as well, not just TD directories.

**Comment by hidetak** [comment]
@egekorkan 

Thank you for your comment.

> @hidetak sounds like a good idea. It would be like using the getThingDescription of node-wot I guess?

Yes, I would use getThingDescription.
I would like to have two timing patterns for outputting the TD: when the server starts and when there is an input to the node.

> Sounds also reasonable and applicable to local network discovery as well, not just TD directories.

I think so.

**Comment by egekorkan** [comment]
Done via #10
