### ISSUE TITLE
Unable to configure client settings or credential settings

### ISSUE THREAD

**Issue by hidetak** [eclipse-thingweb/node-red#9]
Currently, the arguments of the *Server class (e.g., HttpServer class) constructor can be specified in the Binding config of the wot-server-config node, as shown in the screenshot below.
![image](https://github.com/eclipse-thingweb/node-red/assets/39742000/369d7089-72ed-4ba4-9697-45bc72aa5b54)

If I understand correctly, the user would also need to configure the following settings.
1. Server credential settings (settings to be specified on the server side in the argument of the `servient.addCredentials` method)
1. Client settings (Setting to be specified in the argument of the constructor of *ClientFactory)
1. Client credential settings (settings specified by the argument of the client.addCredentials method on the client side)

I think the credential for 1 is set for each Thing, so I would like to add a form to specify the credential and Thing ID to the following configuration screen for each Thing.

![image](https://github.com/eclipse-thingweb/node-red/assets/39742000/0a59e2c5-3db1-488d-9934-4b637d816281)

I would appreciate it if you could point out if my understanding is incorrect.

**Comment by egekorkan** [comment]
> Client credential settings (settings specified by the argument of the client.addCredentials method on the client side)

This is not exactly correct. Server or Client, credentials are always added to the servient, which can have client and/or server sides.

> I think the credential for 1 is set for each Thing, so I would like to add a form to specify the credential and Thing ID to the following configuration screen for each Thing.

This makes sense. Just for username and password, you need two fields and for token only one field.

**Comment by hidetak** [comment]
@egekorkan 
Thanky you for your comment!

> Client credential settings (settings specified by the argument of the client.addCredentials method on the client side)

Sorry, there was a mistake.
 client.addCredentials method -> servient.addCredemtials method

> This makes sense. Just for username and password, you need two fields and for token only one field.

I was going to allow the flexibility to define it in JSON as well as `Server config`, but will consider it.
Thanks for the advice.

**Comment by hidetak** [comment]
I have created a sample to see how to use the authentication feature of Binding HTTP.

https://github.com/hidetak/test-node-wot/tree/main/auth-http/src

If you notice anything, I would be happy to point it out.

**Comment by hidetak** [comment]
PR #10 now supports Basic authentication only.

In this case, I have prepared an input form specifically for Basic Auth, and have made the necessary settings in ServerConfig and Servient.addCredentials.
Therefore, I believe that it is not generic and that the program will need to be modified for each authentication method.

I would appreciate it if you could let me know if there is any discrepancy in this policy.
And if there are other high priority certifications, I would like to consider them.

**Comment by egekorkan** [comment]
> If you notice anything, I would be happy to point it out.

@hidetak this looks good :) @danielpeintner this would be useful in the readmes of HTTP binding no?

**Comment by danielpeintner** [comment]
> @danielpeintner this would be useful in the readmes of HTTP binding no?

@egekorkan what do you mean exactly? 

I think there is a secure example in HTTP, see https://github.com/eclipse-thingweb/node-wot/tree/master/packages/binding-http#server-example
* first a non secure one and 
* a second example how to secure the server

**Comment by egekorkan** [comment]
Done via #10

@danielpeintner what I had meant was a client-server pair available above.
